### ISSUE TITLE
[BUG] %B and %C sorting not working

### ISSUE THREAD

**Issue by ak9250** [martzcodes/OMSCentral#75]
see screenshots for details
![screen shot 2018-08-22 at 6 03 41 pm](https://user-images.githubusercontent.com/6818285/44493433-efb69d00-a635-11e8-905c-bab2ff616965.png)

![screen shot 2018-08-22 at 6 05 53 pm](https://user-images.githubusercontent.com/6818285/44493506-373d2900-a636-11e8-945d-f6fc5533b37b.png)

**Comment by KateRita** [comment]
I saw this issue on the live site, but pulled down the code & this works correctly locally.
I see this commit references addressing this issue:
https://github.com/martzcodes/OMSCentral/commit/7fd2cbfd808e40a7be93390720a339463061a349

But the issue was closed & reopened - so is there an issue with the fix?  or does the issue just need to be closed out?

**Comment by shawnps** [comment]
It seems to be sorting by the user count rather than the percentage. You can see that's the case by hovering over the percentages to see the counts.

**Comment by martzcodes** [comment]
I'm pretty sure this bug kept recurring because the service-worker was being cached indefinitely by the browser as opposed to no caching.  I fixed that in the recent release so this SHOULD be ok now.

Thanks everyone
