### ISSUE TITLE
Miscalculation in course count

### ISSUE THREAD

**Issue by shashankn91** [martzcodes/OMSCentral#81]
I wrote a review for ML and it took some time to get the changes in effect and I wrote the same review again and submitted. Later I realized it is duplicated. I deleted the review but my course count which was supposed to be 6 shows 7. I think course count is done by counting the number of reviews of the user. Need to make it count on the set of courses.

**Comment by martzcodes** [comment]
Yeah, that was odd.  Slightly more complicated than that... you're right that before you deleted I wasn't making sure the course count for a profile page was unique... fixed that.

When a review is deleted from a user I don't actually remove the review if from the user profile... it gets set as null... so that was problem 2.  Fixed that too.  Next time you refresh the page it should be fixed.  Thanks for the report!

**Comment by shashankn91** [comment]
Your commit made sense. But I think there is more to it. Still, I could see count as 7 instead of 6.
